mode: daemonset

presets:
  # enables the k8sattributesprocessor and adds it to the traces, metrics, and logs pipelines
  kubernetesAttributes:
    enabled: true
  # enables the kubeletstatsreceiver and adds it to the metrics pipelines
  kubeletMetrics:
    enabled: true
  # Enables the filelogreceiver and adds it to the logs pipelines
  logsCollection:
    enabled: true

config:
  exporters:
    otlphttp:
      endpoint: "http://openobserve.openobserve.svc.cluster.local:5080/api/default"
      headers:
        Authorization: Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjMK
        stream-name: default

  service:
    pipelines:
      metrics:
        exporters: [ otlphttp ]
      logs:
        exporters: [ otlphttp ]